### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by DemetersSon83** [penguin2048/StockIt#17]
Good afternoon,

I really like what you guys have built here.  I'm currently building a library for portfolio and stock analysis, and would like to bring stock sentiment (from StockTwits) into the analysis.  I was wondering if you'd like to work together on this project.  Alternatively, if you don't have the time or the desire, do you mind if I re-purpose some of your code?  I'll be sure to give you credit.

In case you are interested, here is what I am putting together:
https://github.com/metalcorebear/Markowitzify

MB

**Comment by penguin2048** [comment]
Hello, 
Thanks for showing interest in our project, however currently we don't have the time to actively maintain/participate in it's further development. We have updated the project with MIT license, please feel free to use any part of the repository for your project. 

All the best for you work!

**Comment by DemetersSon83** [comment]
Excellent.  Thanks so much!

MB
